apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: elasticsearch-config
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |-
    cluster.name: "elastic-cluster"
    network.host: 0.0.0.0