apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: default
data:
  elasticsearch.yml: |
    cluster.name: "elastic-cluster"
    node.name: "elasticsearch"
    xpack.security.enabled: false
  log4j2.properties: |
    status = error
    appender.console.type = Console
    appender.console.name = console
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = "[%d{ISO8601}][%-5p][%-25c] %marker%.-10000m%n"
    rootLogger.level = info
    rootLogger.appenderRef.console.ref = console
