apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: default
data:
  elasticsearch.yml: |
    cluster.name: "elastic-cluster"
    node.name: "elasticsearch"
    network.host: 0.0.0.0
    xpack.security.enabled: false
    logger.org.elasticsearch: DEBUG
