---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polaroad-backend
spec:
  selector:
    matchLabels:
      app: polaroad-backend
  template:
    metadata:
      labels:
        app: polaroad-backend
    spec:
      containers:
        - name: polaroad-backend
          # 여러분의 polaroad-backend image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_40d2e5b1304c
          env:
            - name: TZ
              value: Asia/Seoul
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_URL
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: JWT_SECRET_KEY
          resources:
            requests:
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /api/test
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: polaroad-backend
spec:
  selector:
    app: polaroad-backend
  ports:
    - port: 8080
      targetPort: 8080