---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polaroad-backend
spec:
  selector:
    matchLabels:
      app: polaroad-backend
  template:
    metadata:
      labels:
        app: polaroad-backend
    spec:
      containers:
        - name: polaroad-backend
          # 여러분의 polaroad-backend image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_a39a6d339fee
          env:
            - name: TZ
              value: Asia/Seoul
            - name: DATABASE_URL
              value: jdbc:mysql://mysqldb:3306/polaroad
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: JWT_SECRET_KEY
            - name: KAKAO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: KAKAO_API_KEY
            - name: KAKAO_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: KAKAO_REDIRECT_URI
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: REDIS_PASSWORD
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MAIL_PASSWORD
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: GOOGLE_REDIRECT_URI
            - name: GOOGLE_APPLICATION_JSON
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: GOOGLE_APPLICATION_JSON
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx2048m"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/credentials/credentials.json"
          volumeMounts:
            - name: google-credentials-volume
              mountPath: "/etc/credentials"
              readOnly: true
          resources:
            requests:
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /api/test
              port: 8080
      volumes:
        - name: google-credentials-volume
          secret:
            secretName: google-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: polaroad-backend
spec:
  selector:
    app: polaroad-backend
  ports:
    - port: 8080
      targetPort: 8080