apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  JWT_SECRET_KEY: Njg1YTJjZjVjZjQ5MzdkOGEzNTgwNWE1OGMxOGY1MjIyMWZiOGRlMmM2NzI5MzgzNzQwYmYzMjEzNmE1NGZlYjcxYTg4YmZlMDgxMjcyMjUyNjc5NWI3NWZiZTcyNzE2NzhkYTc5NjUxMDRmYjU1YmM2MmE1ZjMzZDNjZDdiMmU=
  DATABASE_URL: amRiYzpteXNxbDovL215c3FsOjMzMDYvcG9sYXJvYWQ/YWxsb3dQdWJsaWNLZXlSZXRyaWV2YWw9dHJ1ZSZ1c2VTU0w9ZmFsc2U=
  DATABASE_USERNAME: ZGJhZG1pbg==
  DATABASE_PASSWORD: amF2YWNvZmZlZTEyQA==
  MYSQL_ROOT_PASSWORD: amF2YWNvZmZlZTEyQA==