apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  serviceName: "elasticsearch"
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: [ "sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data" ]
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "2Gi"
          ports:
            - containerPort: 9200
              name: es-http
            - containerPort: 9300
              name: es-internal
          env:
            - name: "discovery.seed_hosts"
              value: "elasticsearch-0.elasticsearch,elasticsearch-1.elasticsearch,elasticsearch-2.elasticsearch"
            - name: "cluster.initial_master_nodes"
              value: "elasticsearch-0,elasticsearch-1,elasticsearch-2"
            - name: "ES_JAVA_OPTS"
              value: "-Xmx2g -Xms2g"
            - name: "ELASTIC_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: ELASTIC_PASSWORD
            - name: HTTP_PROXY
              value: "krmp-proxy.9rum.cc:3128"
            - name: HTTPS_PROXY
              value: "krmp-proxy.9rum.cc:3128"
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/elasticsearch/config
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: config-volume
          configMap:
            name: elasticsearch-config
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "cinder-tnt-csi"  # MySQL에서 사용되는 StorageClass 이름으로 변경
        resources:
          requests:
            storage: 10Gi