apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  serviceName: "elasticsearch"
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
        - name: copy-config
          image: busybox
          command: ["sh", "-c", "cp /usr/share/elasticsearch/config/* /usr/share/elasticsearch/writable-config/"]
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/elasticsearch/config
              readOnly: true
            - name: writable-config
              mountPath: /usr/share/elasticsearch/writable-config
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
          volumeMounts:
            - name: writable-config
              mountPath: /usr/share/elasticsearch/config
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: config-volume
          configMap:
            name: elasticsearch-config
        - name: writable-config
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "cinder-tnt-csi"
        resources:
          requests:
            storage: 10Gi
