apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - mysqldb.yaml
  - backend.yaml
configMapGenerator:
  - name: init-db
    files:
      - configs/init.sql
