apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldb-data-new
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: mysql-storage-class