package javaiscoffee.polaroad.post;

public enum PostRegion {
    SEOUL,INCHEON,BUSAN,DAEGU,GWANGJU,DAEJEON,ULSAN,GYEONGGIDO,GANGWONDO,
    CHUNGCHEONGNAMDO,CHUNGCHEONGBUKDO,
    JEOLLANAMDO,JEOLLABUKDO,
    GYEONGSANGNAMDO,GYEONGSANGBUKDO,
    JEJUDO
}
